---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - bpfnsapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - bpfnsapplications/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - bpfnsapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - bpfnsprograms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - bpfprograms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - configmaps/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - fentryprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - fentryprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - fentryprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - fexitprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - fexitprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - fexitprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - kprobeprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - kprobeprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - kprobeprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tcnsprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - tcnsprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tcnsprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tcprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - tcprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tcprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tcxnsprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - tcxnsprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tcxnsprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tcxprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - tcxprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tcxprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tracepointprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - tracepointprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tracepointprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - uprobensprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - uprobensprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - uprobensprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - uprobeprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - uprobeprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - uprobeprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - xdpnsprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - xdpnsprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - xdpnsprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - xdpprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - xdpprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - xdpprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - create
  - delete
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator-role
  namespace: bpfman
rules:
- apiGroups:
  - bpfman.io
  resources:
  - bpfnsapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - bpfnsapplications/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - bpfnsapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - bpfnsprograms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - tcnsprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - tcnsprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tcnsprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tcxnsprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - tcxnsprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - tcxnsprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - uprobensprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - uprobensprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - uprobensprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - xdpnsprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - xdpnsprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - xdpnsprograms/status
  verbs:
  - get
  - patch
  - update
