## This is part of the payload deployed by the bpfman-operator NOT kustomize.
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.bpfman.io
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Ephemeral
  storageCapacity: false
  fsGroupPolicy: "ReadWriteOnceWithFSType"
  requiresRepublish: false
  seLinuxMount: false
