# Build the manager binary
ARG BUILDPLATFORM

FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.23 AS bpfman-agent-build

# The following ARGs are set internally by docker/build-push-action in github actions
ARG TARGETOS
ARG TARGETARCH
ARG TARGETPLATFORM

ARG BUILDPLATFORM

RUN echo "TARGETOS=${TARGETOS}  TARGETARCH=${TARGETARCH}  BUILDPLATFORM=${BUILDPLATFORM}  TARGETPLATFORM=${TARGETPLATFORM}"

WORKDIR /usr/src/bpfman-operator

# Copy everything except what's excluded by the .dockerignore file.
COPY . .

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -mod vendor -o bpfman-agent ./cmd/bpfman-agent/main.go


FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.23 AS cri-tools-build
# The following ARGs are set internally by docker/build-push-action in github actions
ARG TARGETOS
ARG TARGETARCH
ARG TARGETPLATFORM

ARG BUILDPLATFORM

RUN echo "TARGETOS=${TARGETOS}  TARGETARCH=${TARGETARCH}  BUILDPLATFORM=${BUILDPLATFORM}  TARGETPLATFORM=${TARGETPLATFORM}"

WORKDIR /usr/src/cri-tools
ARG CRI_REPO_URL=https://github.com/kubernetes-sigs/cri-tools
ARG CRI_REPO_BRANCH=master

RUN git clone --depth 1 --branch $CRI_REPO_BRANCH $CRI_REPO_URL .

# Build
RUN GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} VERSION="latest" make
RUN cp ./build/bin/${TARGETOS}/${TARGETARCH}/crictl .

# Use the fedora minimal image to reduce the size of the final image but still
# be able to easily install extra packages.
FROM --platform=$TARGETPLATFORM quay.io/fedora/fedora-minimal

# The full fedora image can be used for debugging purposes.  To use it, comment
# out the FROM and ARG lines above and uncomment the FROM and ARG lines below.
# FROM fedora:38
# ARG DNF_CMD="dnf"

ARG TARGETARCH
ARG TARGETPLATFORM

WORKDIR /
COPY --from=bpfman-agent-build /usr/src/bpfman-operator/bpfman-agent .

# Install crictl
COPY --from=cri-tools-build /usr/src/cri-tools/crictl /usr/local/bin
RUN chmod +x /usr/local/bin/crictl

ENTRYPOINT ["/bpfman-agent"]
