# permissions for end users to edit bpfapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bpfapplication-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfman-operator
    app.kubernetes.io/part-of: bpfman-operator
    app.kubernetes.io/managed-by: kustomize
  name: bpfapplication-editor-role
rules:
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications/status
  verbs:
  - get
