# permissions for end users to view bpfapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bpfapplication-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfman-operator
    app.kubernetes.io/part-of: bpfman-operator
    app.kubernetes.io/managed-by: kustomize
  name: bpfapplication-viewer-role
rules:
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications/status
  verbs:
  - get
