---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - bpfman.io.bpfman.io
  resources:
  - bpfapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io.bpfman.io
  resources:
  - bpfapplications/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io.bpfman.io
  resources:
  - bpfapplications/status
  verbs:
  - get
  - patch
  - update
