/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/bpfman/bpfman-operator/apis/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// BpfNsApplicationStateLister helps list BpfNsApplicationStates.
// All objects returned here must be treated as read-only.
type BpfNsApplicationStateLister interface {
	// List lists all BpfNsApplicationStates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.BpfNsApplicationState, err error)
	// BpfNsApplicationStates returns an object that can list and get BpfNsApplicationStates.
	BpfNsApplicationStates(namespace string) BpfNsApplicationStateNamespaceLister
	BpfNsApplicationStateListerExpansion
}

// bpfNsApplicationStateLister implements the BpfNsApplicationStateLister interface.
type bpfNsApplicationStateLister struct {
	indexer cache.Indexer
}

// NewBpfNsApplicationStateLister returns a new BpfNsApplicationStateLister.
func NewBpfNsApplicationStateLister(indexer cache.Indexer) BpfNsApplicationStateLister {
	return &bpfNsApplicationStateLister{indexer: indexer}
}

// List lists all BpfNsApplicationStates in the indexer.
func (s *bpfNsApplicationStateLister) List(selector labels.Selector) (ret []*v1alpha1.BpfNsApplicationState, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BpfNsApplicationState))
	})
	return ret, err
}

// BpfNsApplicationStates returns an object that can list and get BpfNsApplicationStates.
func (s *bpfNsApplicationStateLister) BpfNsApplicationStates(namespace string) BpfNsApplicationStateNamespaceLister {
	return bpfNsApplicationStateNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// BpfNsApplicationStateNamespaceLister helps list and get BpfNsApplicationStates.
// All objects returned here must be treated as read-only.
type BpfNsApplicationStateNamespaceLister interface {
	// List lists all BpfNsApplicationStates in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.BpfNsApplicationState, err error)
	// Get retrieves the BpfNsApplicationState from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.BpfNsApplicationState, error)
	BpfNsApplicationStateNamespaceListerExpansion
}

// bpfNsApplicationStateNamespaceLister implements the BpfNsApplicationStateNamespaceLister
// interface.
type bpfNsApplicationStateNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all BpfNsApplicationStates in the indexer for a given namespace.
func (s bpfNsApplicationStateNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.BpfNsApplicationState, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BpfNsApplicationState))
	})
	return ret, err
}

// Get retrieves the BpfNsApplicationState from the indexer for a given namespace and name.
func (s bpfNsApplicationStateNamespaceLister) Get(name string) (*v1alpha1.BpfNsApplicationState, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("bpfnsapplicationstate"), name)
	}
	return obj.(*v1alpha1.BpfNsApplicationState), nil
}
