/*
Copyright 2025 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apisv1alpha1 "github.com/bpfman/bpfman-operator/apis/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterBpfApplicationLister helps list ClusterBpfApplications.
// All objects returned here must be treated as read-only.
type ClusterBpfApplicationLister interface {
	// List lists all ClusterBpfApplications in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisv1alpha1.ClusterBpfApplication, err error)
	// Get retrieves the ClusterBpfApplication from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apisv1alpha1.ClusterBpfApplication, error)
	ClusterBpfApplicationListerExpansion
}

// clusterBpfApplicationLister implements the ClusterBpfApplicationLister interface.
type clusterBpfApplicationLister struct {
	listers.ResourceIndexer[*apisv1alpha1.ClusterBpfApplication]
}

// NewClusterBpfApplicationLister returns a new ClusterBpfApplicationLister.
func NewClusterBpfApplicationLister(indexer cache.Indexer) ClusterBpfApplicationLister {
	return &clusterBpfApplicationLister{listers.New[*apisv1alpha1.ClusterBpfApplication](indexer, apisv1alpha1.Resource("clusterbpfapplication"))}
}
