/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BpfApplicationListerExpansion allows custom methods to be added to
// BpfApplicationLister.
type BpfApplicationListerExpansion interface{}

// BpfNsApplicationListerExpansion allows custom methods to be added to
// BpfNsApplicationLister.
type BpfNsApplicationListerExpansion interface{}

// BpfNsApplicationNamespaceListerExpansion allows custom methods to be added to
// BpfNsApplicationNamespaceLister.
type BpfNsApplicationNamespaceListerExpansion interface{}

// BpfNsProgramListerExpansion allows custom methods to be added to
// BpfNsProgramLister.
type BpfNsProgramListerExpansion interface{}

// BpfNsProgramNamespaceListerExpansion allows custom methods to be added to
// BpfNsProgramNamespaceLister.
type BpfNsProgramNamespaceListerExpansion interface{}

// BpfProgramListerExpansion allows custom methods to be added to
// BpfProgramLister.
type BpfProgramListerExpansion interface{}

// FentryProgramListerExpansion allows custom methods to be added to
// FentryProgramLister.
type FentryProgramListerExpansion interface{}

// FexitProgramListerExpansion allows custom methods to be added to
// FexitProgramLister.
type FexitProgramListerExpansion interface{}

// KprobeProgramListerExpansion allows custom methods to be added to
// KprobeProgramLister.
type KprobeProgramListerExpansion interface{}

// TcNsProgramListerExpansion allows custom methods to be added to
// TcNsProgramLister.
type TcNsProgramListerExpansion interface{}

// TcNsProgramNamespaceListerExpansion allows custom methods to be added to
// TcNsProgramNamespaceLister.
type TcNsProgramNamespaceListerExpansion interface{}

// TcProgramListerExpansion allows custom methods to be added to
// TcProgramLister.
type TcProgramListerExpansion interface{}

// TcxNsProgramListerExpansion allows custom methods to be added to
// TcxNsProgramLister.
type TcxNsProgramListerExpansion interface{}

// TcxNsProgramNamespaceListerExpansion allows custom methods to be added to
// TcxNsProgramNamespaceLister.
type TcxNsProgramNamespaceListerExpansion interface{}

// TcxProgramListerExpansion allows custom methods to be added to
// TcxProgramLister.
type TcxProgramListerExpansion interface{}

// TracepointProgramListerExpansion allows custom methods to be added to
// TracepointProgramLister.
type TracepointProgramListerExpansion interface{}

// UprobeNsProgramListerExpansion allows custom methods to be added to
// UprobeNsProgramLister.
type UprobeNsProgramListerExpansion interface{}

// UprobeNsProgramNamespaceListerExpansion allows custom methods to be added to
// UprobeNsProgramNamespaceLister.
type UprobeNsProgramNamespaceListerExpansion interface{}

// UprobeProgramListerExpansion allows custom methods to be added to
// UprobeProgramLister.
type UprobeProgramListerExpansion interface{}

// XdpNsProgramListerExpansion allows custom methods to be added to
// XdpNsProgramLister.
type XdpNsProgramListerExpansion interface{}

// XdpNsProgramNamespaceListerExpansion allows custom methods to be added to
// XdpNsProgramNamespaceLister.
type XdpNsProgramNamespaceListerExpansion interface{}

// XdpProgramListerExpansion allows custom methods to be added to
// XdpProgramLister.
type XdpProgramListerExpansion interface{}
