apiVersion: bpfman.io/v1alpha1
kind: BpfApplication
metadata:
  labels:
    app.kubernetes.io/name: bpfapplication
    app.kubernetes.io/instance: bpfapplication-sample
    app.kubernetes.io/part-of: bpfman-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: bpfman-operator
  name: bpfapplication-sample
spec:
  # TODO(user): Add fields here
