apiVersion: bpfman.io/v1alpha1
kind: BpfNsApplication
metadata:
  labels:
    app.kubernetes.io/name: bpfnsapplication
  name: bpfapplication-sample
  namespace: acme
spec:
  # Select all nodes
  nodeselector: {}
  bytecode:
    image:
      url: quay.io/bpfman-bytecode/app-test:latest
  programs:
    - bpffunctionname: tc_pass_test
      type: TC
      tc:
        attach_points:
          - interfaceselector:
              interfaces:
                - eth0
            priority: 55
            direction: ingress
            containers:
              pods:
                matchLabels:
                  app: nginx
    - bpffunctionname: tcx_next_test
      type: TCX
      tcx:
        attach_points:
          - interfaceselector:
              interfaces:
                - eth0
            priority: 100
            direction: egress
            containers:
              pods:
                matchLabels:
                  app: nginx
    - bpffunctionname: uprobe_test
      type: Uprobe
      uprobe:
        attach_points:
          - func_name: malloc
            target: libc
            retprobe: false
            containers:
              pods:
                matchLabels:
                  app: nginx
    - bpffunctionname: uretprobe_test
      type: Uprobe
      uprobe:
        attach_points:
          - func_name: malloc
            target: libc
            retprobe: true
            containers:
              pods:
                matchLabels:
                  app: nginx
    - bpffunctionname: xdp_pass_test
      type: XDP
      xdp:
        attach_points:
          - interfaceselector:
              interfaces:
                - eth0
            priority: 100
            containers:
              pods:
                matchLabels:
                  app: nginx
