/*
Copyright 2025 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apisv1alpha1 "github.com/bpfman/bpfman-operator/apis/v1alpha1"
	scheme "github.com/bpfman/bpfman-operator/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BpfApplicationStatesGetter has a method to return a BpfApplicationStateInterface.
// A group's client should implement this interface.
type BpfApplicationStatesGetter interface {
	BpfApplicationStates(namespace string) BpfApplicationStateInterface
}

// BpfApplicationStateInterface has methods to work with BpfApplicationState resources.
type BpfApplicationStateInterface interface {
	Create(ctx context.Context, bpfApplicationState *apisv1alpha1.BpfApplicationState, opts v1.CreateOptions) (*apisv1alpha1.BpfApplicationState, error)
	Update(ctx context.Context, bpfApplicationState *apisv1alpha1.BpfApplicationState, opts v1.UpdateOptions) (*apisv1alpha1.BpfApplicationState, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, bpfApplicationState *apisv1alpha1.BpfApplicationState, opts v1.UpdateOptions) (*apisv1alpha1.BpfApplicationState, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apisv1alpha1.BpfApplicationState, error)
	List(ctx context.Context, opts v1.ListOptions) (*apisv1alpha1.BpfApplicationStateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apisv1alpha1.BpfApplicationState, err error)
	BpfApplicationStateExpansion
}

// bpfApplicationStates implements BpfApplicationStateInterface
type bpfApplicationStates struct {
	*gentype.ClientWithList[*apisv1alpha1.BpfApplicationState, *apisv1alpha1.BpfApplicationStateList]
}

// newBpfApplicationStates returns a BpfApplicationStates
func newBpfApplicationStates(c *BpfmanV1alpha1Client, namespace string) *bpfApplicationStates {
	return &bpfApplicationStates{
		gentype.NewClientWithList[*apisv1alpha1.BpfApplicationState, *apisv1alpha1.BpfApplicationStateList](
			"bpfapplicationstates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apisv1alpha1.BpfApplicationState { return &apisv1alpha1.BpfApplicationState{} },
			func() *apisv1alpha1.BpfApplicationStateList { return &apisv1alpha1.BpfApplicationStateList{} },
		),
	}
}
