/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/bpfman/bpfman-operator/apis/v1alpha1"
	scheme "github.com/bpfman/bpfman-operator/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BpfNsApplicationStatesGetter has a method to return a BpfNsApplicationStateInterface.
// A group's client should implement this interface.
type BpfNsApplicationStatesGetter interface {
	BpfNsApplicationStates(namespace string) BpfNsApplicationStateInterface
}

// BpfNsApplicationStateInterface has methods to work with BpfNsApplicationState resources.
type BpfNsApplicationStateInterface interface {
	Create(ctx context.Context, bpfNsApplicationState *v1alpha1.BpfNsApplicationState, opts v1.CreateOptions) (*v1alpha1.BpfNsApplicationState, error)
	Update(ctx context.Context, bpfNsApplicationState *v1alpha1.BpfNsApplicationState, opts v1.UpdateOptions) (*v1alpha1.BpfNsApplicationState, error)
	UpdateStatus(ctx context.Context, bpfNsApplicationState *v1alpha1.BpfNsApplicationState, opts v1.UpdateOptions) (*v1alpha1.BpfNsApplicationState, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.BpfNsApplicationState, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.BpfNsApplicationStateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BpfNsApplicationState, err error)
	BpfNsApplicationStateExpansion
}

// bpfNsApplicationStates implements BpfNsApplicationStateInterface
type bpfNsApplicationStates struct {
	client rest.Interface
	ns     string
}

// newBpfNsApplicationStates returns a BpfNsApplicationStates
func newBpfNsApplicationStates(c *BpfmanV1alpha1Client, namespace string) *bpfNsApplicationStates {
	return &bpfNsApplicationStates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the bpfNsApplicationState, and returns the corresponding bpfNsApplicationState object, and an error if there is any.
func (c *bpfNsApplicationStates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BpfNsApplicationState, err error) {
	result = &v1alpha1.BpfNsApplicationState{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("bpfnsapplicationstates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BpfNsApplicationStates that match those selectors.
func (c *bpfNsApplicationStates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BpfNsApplicationStateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.BpfNsApplicationStateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("bpfnsapplicationstates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested bpfNsApplicationStates.
func (c *bpfNsApplicationStates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("bpfnsapplicationstates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a bpfNsApplicationState and creates it.  Returns the server's representation of the bpfNsApplicationState, and an error, if there is any.
func (c *bpfNsApplicationStates) Create(ctx context.Context, bpfNsApplicationState *v1alpha1.BpfNsApplicationState, opts v1.CreateOptions) (result *v1alpha1.BpfNsApplicationState, err error) {
	result = &v1alpha1.BpfNsApplicationState{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("bpfnsapplicationstates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bpfNsApplicationState).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a bpfNsApplicationState and updates it. Returns the server's representation of the bpfNsApplicationState, and an error, if there is any.
func (c *bpfNsApplicationStates) Update(ctx context.Context, bpfNsApplicationState *v1alpha1.BpfNsApplicationState, opts v1.UpdateOptions) (result *v1alpha1.BpfNsApplicationState, err error) {
	result = &v1alpha1.BpfNsApplicationState{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("bpfnsapplicationstates").
		Name(bpfNsApplicationState.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bpfNsApplicationState).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *bpfNsApplicationStates) UpdateStatus(ctx context.Context, bpfNsApplicationState *v1alpha1.BpfNsApplicationState, opts v1.UpdateOptions) (result *v1alpha1.BpfNsApplicationState, err error) {
	result = &v1alpha1.BpfNsApplicationState{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("bpfnsapplicationstates").
		Name(bpfNsApplicationState.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bpfNsApplicationState).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the bpfNsApplicationState and deletes it. Returns an error if one occurs.
func (c *bpfNsApplicationStates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("bpfnsapplicationstates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *bpfNsApplicationStates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("bpfnsapplicationstates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched bpfNsApplicationState.
func (c *bpfNsApplicationStates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BpfNsApplicationState, err error) {
	result = &v1alpha1.BpfNsApplicationState{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("bpfnsapplicationstates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
