/*
Copyright 2025 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apisv1alpha1 "github.com/bpfman/bpfman-operator/apis/v1alpha1"
	scheme "github.com/bpfman/bpfman-operator/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterBpfApplicationsGetter has a method to return a ClusterBpfApplicationInterface.
// A group's client should implement this interface.
type ClusterBpfApplicationsGetter interface {
	ClusterBpfApplications() ClusterBpfApplicationInterface
}

// ClusterBpfApplicationInterface has methods to work with ClusterBpfApplication resources.
type ClusterBpfApplicationInterface interface {
	Create(ctx context.Context, clusterBpfApplication *apisv1alpha1.ClusterBpfApplication, opts v1.CreateOptions) (*apisv1alpha1.ClusterBpfApplication, error)
	Update(ctx context.Context, clusterBpfApplication *apisv1alpha1.ClusterBpfApplication, opts v1.UpdateOptions) (*apisv1alpha1.ClusterBpfApplication, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterBpfApplication *apisv1alpha1.ClusterBpfApplication, opts v1.UpdateOptions) (*apisv1alpha1.ClusterBpfApplication, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apisv1alpha1.ClusterBpfApplication, error)
	List(ctx context.Context, opts v1.ListOptions) (*apisv1alpha1.ClusterBpfApplicationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apisv1alpha1.ClusterBpfApplication, err error)
	ClusterBpfApplicationExpansion
}

// clusterBpfApplications implements ClusterBpfApplicationInterface
type clusterBpfApplications struct {
	*gentype.ClientWithList[*apisv1alpha1.ClusterBpfApplication, *apisv1alpha1.ClusterBpfApplicationList]
}

// newClusterBpfApplications returns a ClusterBpfApplications
func newClusterBpfApplications(c *BpfmanV1alpha1Client) *clusterBpfApplications {
	return &clusterBpfApplications{
		gentype.NewClientWithList[*apisv1alpha1.ClusterBpfApplication, *apisv1alpha1.ClusterBpfApplicationList](
			"clusterbpfapplications",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *apisv1alpha1.ClusterBpfApplication { return &apisv1alpha1.ClusterBpfApplication{} },
			func() *apisv1alpha1.ClusterBpfApplicationList { return &apisv1alpha1.ClusterBpfApplicationList{} },
		),
	}
}
