/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/bpfman/bpfman-operator/apis/v1alpha1"
	scheme "github.com/bpfman/bpfman-operator/pkg/client/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TcxNsProgramsGetter has a method to return a TcxNsProgramInterface.
// A group's client should implement this interface.
type TcxNsProgramsGetter interface {
	TcxNsPrograms(namespace string) TcxNsProgramInterface
}

// TcxNsProgramInterface has methods to work with TcxNsProgram resources.
type TcxNsProgramInterface interface {
	Create(ctx context.Context, tcxNsProgram *v1alpha1.TcxNsProgram, opts v1.CreateOptions) (*v1alpha1.TcxNsProgram, error)
	Update(ctx context.Context, tcxNsProgram *v1alpha1.TcxNsProgram, opts v1.UpdateOptions) (*v1alpha1.TcxNsProgram, error)
	UpdateStatus(ctx context.Context, tcxNsProgram *v1alpha1.TcxNsProgram, opts v1.UpdateOptions) (*v1alpha1.TcxNsProgram, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TcxNsProgram, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TcxNsProgramList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TcxNsProgram, err error)
	TcxNsProgramExpansion
}

// tcxNsPrograms implements TcxNsProgramInterface
type tcxNsPrograms struct {
	client rest.Interface
	ns     string
}

// newTcxNsPrograms returns a TcxNsPrograms
func newTcxNsPrograms(c *BpfmanV1alpha1Client, namespace string) *tcxNsPrograms {
	return &tcxNsPrograms{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the tcxNsProgram, and returns the corresponding tcxNsProgram object, and an error if there is any.
func (c *tcxNsPrograms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TcxNsProgram, err error) {
	result = &v1alpha1.TcxNsProgram{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tcxnsprograms").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TcxNsPrograms that match those selectors.
func (c *tcxNsPrograms) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TcxNsProgramList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TcxNsProgramList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tcxnsprograms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tcxNsPrograms.
func (c *tcxNsPrograms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("tcxnsprograms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a tcxNsProgram and creates it.  Returns the server's representation of the tcxNsProgram, and an error, if there is any.
func (c *tcxNsPrograms) Create(ctx context.Context, tcxNsProgram *v1alpha1.TcxNsProgram, opts v1.CreateOptions) (result *v1alpha1.TcxNsProgram, err error) {
	result = &v1alpha1.TcxNsProgram{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("tcxnsprograms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tcxNsProgram).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a tcxNsProgram and updates it. Returns the server's representation of the tcxNsProgram, and an error, if there is any.
func (c *tcxNsPrograms) Update(ctx context.Context, tcxNsProgram *v1alpha1.TcxNsProgram, opts v1.UpdateOptions) (result *v1alpha1.TcxNsProgram, err error) {
	result = &v1alpha1.TcxNsProgram{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tcxnsprograms").
		Name(tcxNsProgram.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tcxNsProgram).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *tcxNsPrograms) UpdateStatus(ctx context.Context, tcxNsProgram *v1alpha1.TcxNsProgram, opts v1.UpdateOptions) (result *v1alpha1.TcxNsProgram, err error) {
	result = &v1alpha1.TcxNsProgram{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tcxnsprograms").
		Name(tcxNsProgram.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tcxNsProgram).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the tcxNsProgram and deletes it. Returns an error if one occurs.
func (c *tcxNsPrograms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tcxnsprograms").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tcxNsPrograms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tcxnsprograms").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched tcxNsProgram.
func (c *tcxNsPrograms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TcxNsProgram, err error) {
	result = &v1alpha1.TcxNsProgram{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("tcxnsprograms").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
