apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    openshift.io/node-selector: ""
    openshift.io/description: Openshift bpfman components
    workload.openshift.io/allowed: management
  name: system
---
apiVersion: bpfman.io/v1alpha1
kind: Config
metadata:
  name: config
spec:
  ## Can be configured at runtime
  namespace: bpfman
  logLevel: info
  agent:
    logLevel: info
