/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/bpfman/bpfman-operator/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBpfNsApplicationStates implements BpfNsApplicationStateInterface
type FakeBpfNsApplicationStates struct {
	Fake *FakeBpfmanV1alpha1
	ns   string
}

var bpfnsapplicationstatesResource = v1alpha1.SchemeGroupVersion.WithResource("bpfnsapplicationstates")

var bpfnsapplicationstatesKind = v1alpha1.SchemeGroupVersion.WithKind("BpfNsApplicationState")

// Get takes name of the bpfNsApplicationState, and returns the corresponding bpfNsApplicationState object, and an error if there is any.
func (c *FakeBpfNsApplicationStates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BpfNsApplicationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bpfnsapplicationstatesResource, c.ns, name), &v1alpha1.BpfNsApplicationState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfNsApplicationState), err
}

// List takes label and field selectors, and returns the list of BpfNsApplicationStates that match those selectors.
func (c *FakeBpfNsApplicationStates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BpfNsApplicationStateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bpfnsapplicationstatesResource, bpfnsapplicationstatesKind, c.ns, opts), &v1alpha1.BpfNsApplicationStateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BpfNsApplicationStateList{ListMeta: obj.(*v1alpha1.BpfNsApplicationStateList).ListMeta}
	for _, item := range obj.(*v1alpha1.BpfNsApplicationStateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bpfNsApplicationStates.
func (c *FakeBpfNsApplicationStates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bpfnsapplicationstatesResource, c.ns, opts))

}

// Create takes the representation of a bpfNsApplicationState and creates it.  Returns the server's representation of the bpfNsApplicationState, and an error, if there is any.
func (c *FakeBpfNsApplicationStates) Create(ctx context.Context, bpfNsApplicationState *v1alpha1.BpfNsApplicationState, opts v1.CreateOptions) (result *v1alpha1.BpfNsApplicationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bpfnsapplicationstatesResource, c.ns, bpfNsApplicationState), &v1alpha1.BpfNsApplicationState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfNsApplicationState), err
}

// Update takes the representation of a bpfNsApplicationState and updates it. Returns the server's representation of the bpfNsApplicationState, and an error, if there is any.
func (c *FakeBpfNsApplicationStates) Update(ctx context.Context, bpfNsApplicationState *v1alpha1.BpfNsApplicationState, opts v1.UpdateOptions) (result *v1alpha1.BpfNsApplicationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bpfnsapplicationstatesResource, c.ns, bpfNsApplicationState), &v1alpha1.BpfNsApplicationState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfNsApplicationState), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBpfNsApplicationStates) UpdateStatus(ctx context.Context, bpfNsApplicationState *v1alpha1.BpfNsApplicationState, opts v1.UpdateOptions) (*v1alpha1.BpfNsApplicationState, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(bpfnsapplicationstatesResource, "status", c.ns, bpfNsApplicationState), &v1alpha1.BpfNsApplicationState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfNsApplicationState), err
}

// Delete takes name of the bpfNsApplicationState and deletes it. Returns an error if one occurs.
func (c *FakeBpfNsApplicationStates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(bpfnsapplicationstatesResource, c.ns, name, opts), &v1alpha1.BpfNsApplicationState{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBpfNsApplicationStates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bpfnsapplicationstatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BpfNsApplicationStateList{})
	return err
}

// Patch applies the patch and returns the patched bpfNsApplicationState.
func (c *FakeBpfNsApplicationStates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BpfNsApplicationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bpfnsapplicationstatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.BpfNsApplicationState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfNsApplicationState), err
}
