/*
Copyright 2025 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/bpfman/bpfman-operator/apis/v1alpha1"
	apisv1alpha1 "github.com/bpfman/bpfman-operator/pkg/client/clientset/typed/apis/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeBpfApplicationStates implements BpfApplicationStateInterface
type fakeBpfApplicationStates struct {
	*gentype.FakeClientWithList[*v1alpha1.BpfApplicationState, *v1alpha1.BpfApplicationStateList]
	Fake *FakeBpfmanV1alpha1
}

func newFakeBpfApplicationStates(fake *FakeBpfmanV1alpha1, namespace string) apisv1alpha1.BpfApplicationStateInterface {
	return &fakeBpfApplicationStates{
		gentype.NewFakeClientWithList[*v1alpha1.BpfApplicationState, *v1alpha1.BpfApplicationStateList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("bpfapplicationstates"),
			v1alpha1.SchemeGroupVersion.WithKind("BpfApplicationState"),
			func() *v1alpha1.BpfApplicationState { return &v1alpha1.BpfApplicationState{} },
			func() *v1alpha1.BpfApplicationStateList { return &v1alpha1.BpfApplicationStateList{} },
			func(dst, src *v1alpha1.BpfApplicationStateList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.BpfApplicationStateList) []*v1alpha1.BpfApplicationState {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.BpfApplicationStateList, items []*v1alpha1.BpfApplicationState) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
