/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/bpfman/bpfman-operator/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBpfApplicationNodes implements BpfApplicationNodeInterface
type FakeBpfApplicationNodes struct {
	Fake *FakeBpfmanV1alpha1
}

var bpfapplicationnodesResource = v1alpha1.SchemeGroupVersion.WithResource("bpfapplicationnodes")

var bpfapplicationnodesKind = v1alpha1.SchemeGroupVersion.WithKind("BpfApplicationNode")

// Get takes name of the bpfApplicationNode, and returns the corresponding bpfApplicationNode object, and an error if there is any.
func (c *FakeBpfApplicationNodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BpfApplicationNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(bpfapplicationnodesResource, name), &v1alpha1.BpfApplicationNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfApplicationNode), err
}

// List takes label and field selectors, and returns the list of BpfApplicationNodes that match those selectors.
func (c *FakeBpfApplicationNodes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BpfApplicationNodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(bpfapplicationnodesResource, bpfapplicationnodesKind, opts), &v1alpha1.BpfApplicationNodeList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BpfApplicationNodeList{ListMeta: obj.(*v1alpha1.BpfApplicationNodeList).ListMeta}
	for _, item := range obj.(*v1alpha1.BpfApplicationNodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bpfApplicationNodes.
func (c *FakeBpfApplicationNodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(bpfapplicationnodesResource, opts))
}

// Create takes the representation of a bpfApplicationNode and creates it.  Returns the server's representation of the bpfApplicationNode, and an error, if there is any.
func (c *FakeBpfApplicationNodes) Create(ctx context.Context, bpfApplicationNode *v1alpha1.BpfApplicationNode, opts v1.CreateOptions) (result *v1alpha1.BpfApplicationNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(bpfapplicationnodesResource, bpfApplicationNode), &v1alpha1.BpfApplicationNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfApplicationNode), err
}

// Update takes the representation of a bpfApplicationNode and updates it. Returns the server's representation of the bpfApplicationNode, and an error, if there is any.
func (c *FakeBpfApplicationNodes) Update(ctx context.Context, bpfApplicationNode *v1alpha1.BpfApplicationNode, opts v1.UpdateOptions) (result *v1alpha1.BpfApplicationNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(bpfapplicationnodesResource, bpfApplicationNode), &v1alpha1.BpfApplicationNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfApplicationNode), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBpfApplicationNodes) UpdateStatus(ctx context.Context, bpfApplicationNode *v1alpha1.BpfApplicationNode, opts v1.UpdateOptions) (*v1alpha1.BpfApplicationNode, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(bpfapplicationnodesResource, "status", bpfApplicationNode), &v1alpha1.BpfApplicationNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfApplicationNode), err
}

// Delete takes name of the bpfApplicationNode and deletes it. Returns an error if one occurs.
func (c *FakeBpfApplicationNodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(bpfapplicationnodesResource, name, opts), &v1alpha1.BpfApplicationNode{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBpfApplicationNodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(bpfapplicationnodesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BpfApplicationNodeList{})
	return err
}

// Patch applies the patch and returns the patched bpfApplicationNode.
func (c *FakeBpfApplicationNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BpfApplicationNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bpfapplicationnodesResource, name, pt, data, subresources...), &v1alpha1.BpfApplicationNode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfApplicationNode), err
}
