/*
Copyright 2025 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/bpfman/bpfman-operator/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterBpfApplicationStates implements ClusterBpfApplicationStateInterface
type FakeClusterBpfApplicationStates struct {
	Fake *FakeBpfmanV1alpha1
}

var clusterbpfapplicationstatesResource = v1alpha1.SchemeGroupVersion.WithResource("clusterbpfapplicationstates")

var clusterbpfapplicationstatesKind = v1alpha1.SchemeGroupVersion.WithKind("ClusterBpfApplicationState")

// Get takes name of the clusterBpfApplicationState, and returns the corresponding clusterBpfApplicationState object, and an error if there is any.
func (c *FakeClusterBpfApplicationStates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterBpfApplicationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterbpfapplicationstatesResource, name), &v1alpha1.ClusterBpfApplicationState{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterBpfApplicationState), err
}

// List takes label and field selectors, and returns the list of ClusterBpfApplicationStates that match those selectors.
func (c *FakeClusterBpfApplicationStates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterBpfApplicationStateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterbpfapplicationstatesResource, clusterbpfapplicationstatesKind, opts), &v1alpha1.ClusterBpfApplicationStateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterBpfApplicationStateList{ListMeta: obj.(*v1alpha1.ClusterBpfApplicationStateList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterBpfApplicationStateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterBpfApplicationStates.
func (c *FakeClusterBpfApplicationStates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterbpfapplicationstatesResource, opts))
}

// Create takes the representation of a clusterBpfApplicationState and creates it.  Returns the server's representation of the clusterBpfApplicationState, and an error, if there is any.
func (c *FakeClusterBpfApplicationStates) Create(ctx context.Context, clusterBpfApplicationState *v1alpha1.ClusterBpfApplicationState, opts v1.CreateOptions) (result *v1alpha1.ClusterBpfApplicationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterbpfapplicationstatesResource, clusterBpfApplicationState), &v1alpha1.ClusterBpfApplicationState{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterBpfApplicationState), err
}

// Update takes the representation of a clusterBpfApplicationState and updates it. Returns the server's representation of the clusterBpfApplicationState, and an error, if there is any.
func (c *FakeClusterBpfApplicationStates) Update(ctx context.Context, clusterBpfApplicationState *v1alpha1.ClusterBpfApplicationState, opts v1.UpdateOptions) (result *v1alpha1.ClusterBpfApplicationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterbpfapplicationstatesResource, clusterBpfApplicationState), &v1alpha1.ClusterBpfApplicationState{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterBpfApplicationState), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterBpfApplicationStates) UpdateStatus(ctx context.Context, clusterBpfApplicationState *v1alpha1.ClusterBpfApplicationState, opts v1.UpdateOptions) (*v1alpha1.ClusterBpfApplicationState, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterbpfapplicationstatesResource, "status", clusterBpfApplicationState), &v1alpha1.ClusterBpfApplicationState{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterBpfApplicationState), err
}

// Delete takes name of the clusterBpfApplicationState and deletes it. Returns an error if one occurs.
func (c *FakeClusterBpfApplicationStates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clusterbpfapplicationstatesResource, name, opts), &v1alpha1.ClusterBpfApplicationState{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterBpfApplicationStates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterbpfapplicationstatesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterBpfApplicationStateList{})
	return err
}

// Patch applies the patch and returns the patched clusterBpfApplicationState.
func (c *FakeClusterBpfApplicationStates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterBpfApplicationState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterbpfapplicationstatesResource, name, pt, data, subresources...), &v1alpha1.ClusterBpfApplicationState{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterBpfApplicationState), err
}
