/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/bpfman/bpfman-operator/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeUprobeNsPrograms implements UprobeNsProgramInterface
type FakeUprobeNsPrograms struct {
	Fake *FakeBpfmanV1alpha1
	ns   string
}

var uprobensprogramsResource = v1alpha1.SchemeGroupVersion.WithResource("uprobensprograms")

var uprobensprogramsKind = v1alpha1.SchemeGroupVersion.WithKind("UprobeNsProgram")

// Get takes name of the uprobeNsProgram, and returns the corresponding uprobeNsProgram object, and an error if there is any.
func (c *FakeUprobeNsPrograms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.UprobeNsProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(uprobensprogramsResource, c.ns, name), &v1alpha1.UprobeNsProgram{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UprobeNsProgram), err
}

// List takes label and field selectors, and returns the list of UprobeNsPrograms that match those selectors.
func (c *FakeUprobeNsPrograms) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UprobeNsProgramList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(uprobensprogramsResource, uprobensprogramsKind, c.ns, opts), &v1alpha1.UprobeNsProgramList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.UprobeNsProgramList{ListMeta: obj.(*v1alpha1.UprobeNsProgramList).ListMeta}
	for _, item := range obj.(*v1alpha1.UprobeNsProgramList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested uprobeNsPrograms.
func (c *FakeUprobeNsPrograms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(uprobensprogramsResource, c.ns, opts))

}

// Create takes the representation of a uprobeNsProgram and creates it.  Returns the server's representation of the uprobeNsProgram, and an error, if there is any.
func (c *FakeUprobeNsPrograms) Create(ctx context.Context, uprobeNsProgram *v1alpha1.UprobeNsProgram, opts v1.CreateOptions) (result *v1alpha1.UprobeNsProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(uprobensprogramsResource, c.ns, uprobeNsProgram), &v1alpha1.UprobeNsProgram{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UprobeNsProgram), err
}

// Update takes the representation of a uprobeNsProgram and updates it. Returns the server's representation of the uprobeNsProgram, and an error, if there is any.
func (c *FakeUprobeNsPrograms) Update(ctx context.Context, uprobeNsProgram *v1alpha1.UprobeNsProgram, opts v1.UpdateOptions) (result *v1alpha1.UprobeNsProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(uprobensprogramsResource, c.ns, uprobeNsProgram), &v1alpha1.UprobeNsProgram{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UprobeNsProgram), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeUprobeNsPrograms) UpdateStatus(ctx context.Context, uprobeNsProgram *v1alpha1.UprobeNsProgram, opts v1.UpdateOptions) (*v1alpha1.UprobeNsProgram, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(uprobensprogramsResource, "status", c.ns, uprobeNsProgram), &v1alpha1.UprobeNsProgram{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UprobeNsProgram), err
}

// Delete takes name of the uprobeNsProgram and deletes it. Returns an error if one occurs.
func (c *FakeUprobeNsPrograms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(uprobensprogramsResource, c.ns, name, opts), &v1alpha1.UprobeNsProgram{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUprobeNsPrograms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(uprobensprogramsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.UprobeNsProgramList{})
	return err
}

// Patch applies the patch and returns the patched uprobeNsProgram.
func (c *FakeUprobeNsPrograms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UprobeNsProgram, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(uprobensprogramsResource, c.ns, name, pt, data, subresources...), &v1alpha1.UprobeNsProgram{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.UprobeNsProgram), err
}
