/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/bpfman/bpfman-operator/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBpfApplications implements BpfApplicationInterface
type FakeBpfApplications struct {
	Fake *FakeBpfmanV1alpha1
	ns   string
}

var bpfapplicationsResource = v1alpha1.SchemeGroupVersion.WithResource("bpfapplications")

var bpfapplicationsKind = v1alpha1.SchemeGroupVersion.WithKind("BpfApplication")

// Get takes name of the bpfApplication, and returns the corresponding bpfApplication object, and an error if there is any.
func (c *FakeBpfApplications) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BpfApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bpfapplicationsResource, c.ns, name), &v1alpha1.BpfApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfApplication), err
}

// List takes label and field selectors, and returns the list of BpfApplications that match those selectors.
func (c *FakeBpfApplications) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BpfApplicationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bpfapplicationsResource, bpfapplicationsKind, c.ns, opts), &v1alpha1.BpfApplicationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BpfApplicationList{ListMeta: obj.(*v1alpha1.BpfApplicationList).ListMeta}
	for _, item := range obj.(*v1alpha1.BpfApplicationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bpfApplications.
func (c *FakeBpfApplications) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bpfapplicationsResource, c.ns, opts))

}

// Create takes the representation of a bpfApplication and creates it.  Returns the server's representation of the bpfApplication, and an error, if there is any.
func (c *FakeBpfApplications) Create(ctx context.Context, bpfApplication *v1alpha1.BpfApplication, opts v1.CreateOptions) (result *v1alpha1.BpfApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bpfapplicationsResource, c.ns, bpfApplication), &v1alpha1.BpfApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfApplication), err
}

// Update takes the representation of a bpfApplication and updates it. Returns the server's representation of the bpfApplication, and an error, if there is any.
func (c *FakeBpfApplications) Update(ctx context.Context, bpfApplication *v1alpha1.BpfApplication, opts v1.UpdateOptions) (result *v1alpha1.BpfApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bpfapplicationsResource, c.ns, bpfApplication), &v1alpha1.BpfApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfApplication), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBpfApplications) UpdateStatus(ctx context.Context, bpfApplication *v1alpha1.BpfApplication, opts v1.UpdateOptions) (*v1alpha1.BpfApplication, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(bpfapplicationsResource, "status", c.ns, bpfApplication), &v1alpha1.BpfApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfApplication), err
}

// Delete takes name of the bpfApplication and deletes it. Returns an error if one occurs.
func (c *FakeBpfApplications) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(bpfapplicationsResource, c.ns, name, opts), &v1alpha1.BpfApplication{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBpfApplications) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bpfapplicationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BpfApplicationList{})
	return err
}

// Patch applies the patch and returns the patched bpfApplication.
func (c *FakeBpfApplications) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BpfApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bpfapplicationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.BpfApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BpfApplication), err
}
