apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/bpfman/bpfman-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" &&
      (".tekton/***".pathChanged() ||
      "apis/***".pathChanged() ||
      "controllers/***".pathChanged() ||
      "cmd/***".pathChanged() ||
      "Containerfile.bpfman-operator.openshift".pathChanged() ||
      "go.mod".pathChanged() ||
      "go.sum".pathChanged() ||
      "hack/***".pathChanged() ||
      "Makefile".pathChanged() ||
      "pkg/***".pathChanged() ||
      "internal/***".pathChanged() ||
      "test/***".pathChanged() ||
      "vendor/***".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: bpfman-operator
    appstudio.openshift.io/component: bpfman-operator
    pipelines.appstudio.openshift.io/type: build
  name: bpfman-operator-on-pull-request
  namespace: ocp-bpfman-tenant
spec:
  params:
  - name: build-source-image
    value: "true"
  #- name: prefetch-input
  #  value: '{"type": "gomod", "path": "."}'
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocp-bpfman-tenant/bpfman-operator/bpfman-operator:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Containerfile.bpfman-operator.openshift
  - name: path-context
    value: .
  - name: build-platforms
    value:
      - localhost
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
