apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/bpfman/bpfman-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    build.appstudio.openshift.io/build-nudge-files: "hack/update_bundle.sh"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: bpfman-operator
    appstudio.openshift.io/component: bpfman-agent
    pipelines.appstudio.openshift.io/type: build
  name: bpfman-agent-on-push
  namespace: ocp-bpfman-tenant
spec:
  params:
  - name: build-source-image
    value: "true"
  #- name: prefetch-input
  #  value: '{"type": "gomod", "path": "."}'
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocp-bpfman-tenant/bpfman-operator/bpfman-agent:{{revision}}
  - name: dockerfile
    value: Containerfile.bpfman-agent.openshift
  - name: path-context
    value: .
  - name: build-platforms
    value:
      - localhost
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
