//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplication) DeepCopyInto(out *BpfApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplication.
func (in *BpfApplication) DeepCopy() *BpfApplication {
	if in == nil {
		return nil
	}
	out := new(BpfApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplicationList) DeepCopyInto(out *BpfApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BpfApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplicationList.
func (in *BpfApplicationList) DeepCopy() *BpfApplicationList {
	if in == nil {
		return nil
	}
	out := new(BpfApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplicationProgram) DeepCopyInto(out *BpfApplicationProgram) {
	*out = *in
	if in.XDP != nil {
		in, out := &in.XDP, &out.XDP
		*out = new(XdpProgramSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TC != nil {
		in, out := &in.TC, &out.TC
		*out = new(TcProgramSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TCX != nil {
		in, out := &in.TCX, &out.TCX
		*out = new(TcProgramSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Fentry != nil {
		in, out := &in.Fentry, &out.Fentry
		*out = new(FentryProgramSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Fexit != nil {
		in, out := &in.Fexit, &out.Fexit
		*out = new(FentryProgramSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Kprobe != nil {
		in, out := &in.Kprobe, &out.Kprobe
		*out = new(KprobeProgramSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Kretprobe != nil {
		in, out := &in.Kretprobe, &out.Kretprobe
		*out = new(KprobeProgramSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Uprobe != nil {
		in, out := &in.Uprobe, &out.Uprobe
		*out = new(UprobeProgramSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Uretprobe != nil {
		in, out := &in.Uretprobe, &out.Uretprobe
		*out = new(UprobeProgramSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Tracepoint != nil {
		in, out := &in.Tracepoint, &out.Tracepoint
		*out = new(TracepointProgramSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplicationProgram.
func (in *BpfApplicationProgram) DeepCopy() *BpfApplicationProgram {
	if in == nil {
		return nil
	}
	out := new(BpfApplicationProgram)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplicationSpec) DeepCopyInto(out *BpfApplicationSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	if in.GlobalData != nil {
		in, out := &in.GlobalData, &out.GlobalData
		*out = make(map[string][]byte, len(*in))
		for key, val := range *in {
			var outVal []byte
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]byte, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Programs != nil {
		in, out := &in.Programs, &out.Programs
		*out = make([]BpfApplicationProgram, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplicationSpec.
func (in *BpfApplicationSpec) DeepCopy() *BpfApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(BpfApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplicationStatus) DeepCopyInto(out *BpfApplicationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplicationStatus.
func (in *BpfApplicationStatus) DeepCopy() *BpfApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(BpfApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplicationWebhook) DeepCopyInto(out *BpfApplicationWebhook) {
	*out = *in
	in.BpfApplication.DeepCopyInto(&out.BpfApplication)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplicationWebhook.
func (in *BpfApplicationWebhook) DeepCopy() *BpfApplicationWebhook {
	if in == nil {
		return nil
	}
	out := new(BpfApplicationWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfProgramCommon) DeepCopyInto(out *BpfProgramCommon) {
	*out = *in
	in.ByteCode.DeepCopyInto(&out.ByteCode)
	in.MapOwnerSelector.DeepCopyInto(&out.MapOwnerSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfProgramCommon.
func (in *BpfProgramCommon) DeepCopy() *BpfProgramCommon {
	if in == nil {
		return nil
	}
	out := new(BpfProgramCommon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BytecodeImage) DeepCopyInto(out *BytecodeImage) {
	*out = *in
	if in.ImagePullSecret != nil {
		in, out := &in.ImagePullSecret, &out.ImagePullSecret
		*out = new(ImagePullSecretSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BytecodeImage.
func (in *BytecodeImage) DeepCopy() *BytecodeImage {
	if in == nil {
		return nil
	}
	out := new(BytecodeImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BytecodeSelector) DeepCopyInto(out *BytecodeSelector) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(BytecodeImage)
		(*in).DeepCopyInto(*out)
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BytecodeSelector.
func (in *BytecodeSelector) DeepCopy() *BytecodeSelector {
	if in == nil {
		return nil
	}
	out := new(BytecodeSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerSelector) DeepCopyInto(out *ContainerSelector) {
	*out = *in
	in.Pods.DeepCopyInto(&out.Pods)
	if in.ContainerNames != nil {
		in, out := &in.ContainerNames, &out.ContainerNames
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerSelector.
func (in *ContainerSelector) DeepCopy() *ContainerSelector {
	if in == nil {
		return nil
	}
	out := new(ContainerSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FentryProgramSpec) DeepCopyInto(out *FentryProgramSpec) {
	*out = *in
	in.BpfProgramCommon.DeepCopyInto(&out.BpfProgramCommon)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FentryProgramSpec.
func (in *FentryProgramSpec) DeepCopy() *FentryProgramSpec {
	if in == nil {
		return nil
	}
	out := new(FentryProgramSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSecretSelector) DeepCopyInto(out *ImagePullSecretSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSecretSelector.
func (in *ImagePullSecretSelector) DeepCopy() *ImagePullSecretSelector {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecretSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceSelector) DeepCopyInto(out *InterfaceSelector) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.PrimaryNodeInterface != nil {
		in, out := &in.PrimaryNodeInterface, &out.PrimaryNodeInterface
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceSelector.
func (in *InterfaceSelector) DeepCopy() *InterfaceSelector {
	if in == nil {
		return nil
	}
	out := new(InterfaceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KprobeProgramSpec) DeepCopyInto(out *KprobeProgramSpec) {
	*out = *in
	in.BpfProgramCommon.DeepCopyInto(&out.BpfProgramCommon)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KprobeProgramSpec.
func (in *KprobeProgramSpec) DeepCopy() *KprobeProgramSpec {
	if in == nil {
		return nil
	}
	out := new(KprobeProgramSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcProgramSpec) DeepCopyInto(out *TcProgramSpec) {
	*out = *in
	in.BpfProgramCommon.DeepCopyInto(&out.BpfProgramCommon)
	in.InterfaceSelector.DeepCopyInto(&out.InterfaceSelector)
	if in.ProceedOn != nil {
		in, out := &in.ProceedOn, &out.ProceedOn
		*out = make([]TcProceedOnValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcProgramSpec.
func (in *TcProgramSpec) DeepCopy() *TcProgramSpec {
	if in == nil {
		return nil
	}
	out := new(TcProgramSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracepointProgramSpec) DeepCopyInto(out *TracepointProgramSpec) {
	*out = *in
	in.BpfProgramCommon.DeepCopyInto(&out.BpfProgramCommon)
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracepointProgramSpec.
func (in *TracepointProgramSpec) DeepCopy() *TracepointProgramSpec {
	if in == nil {
		return nil
	}
	out := new(TracepointProgramSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UprobeProgramSpec) DeepCopyInto(out *UprobeProgramSpec) {
	*out = *in
	in.BpfProgramCommon.DeepCopyInto(&out.BpfProgramCommon)
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = new(ContainerSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UprobeProgramSpec.
func (in *UprobeProgramSpec) DeepCopy() *UprobeProgramSpec {
	if in == nil {
		return nil
	}
	out := new(UprobeProgramSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdpProgramSpec) DeepCopyInto(out *XdpProgramSpec) {
	*out = *in
	in.BpfProgramCommon.DeepCopyInto(&out.BpfProgramCommon)
	in.InterfaceSelector.DeepCopyInto(&out.InterfaceSelector)
	if in.ProceedOn != nil {
		in, out := &in.ProceedOn, &out.ProceedOn
		*out = make([]XdpProceedOnValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdpProgramSpec.
func (in *XdpProgramSpec) DeepCopy() *XdpProgramSpec {
	if in == nil {
		return nil
	}
	out := new(XdpProgramSpec)
	in.DeepCopyInto(out)
	return out
}
