//go:build !ignore_autogenerated

/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachInfoStateCommon) DeepCopyInto(out *AttachInfoStateCommon) {
	*out = *in
	if in.AttachId != nil {
		in, out := &in.AttachId, &out.AttachId
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachInfoStateCommon.
func (in *AttachInfoStateCommon) DeepCopy() *AttachInfoStateCommon {
	if in == nil {
		return nil
	}
	out := new(AttachInfoStateCommon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfAppCommon) DeepCopyInto(out *BpfAppCommon) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	if in.GlobalData != nil {
		in, out := &in.GlobalData, &out.GlobalData
		*out = make(map[string][]byte, len(*in))
		for key, val := range *in {
			var outVal []byte
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]byte, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	in.ByteCode.DeepCopyInto(&out.ByteCode)
	if in.MapOwnerSelector != nil {
		in, out := &in.MapOwnerSelector, &out.MapOwnerSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfAppCommon.
func (in *BpfAppCommon) DeepCopy() *BpfAppCommon {
	if in == nil {
		return nil
	}
	out := new(BpfAppCommon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfAppStatus) DeepCopyInto(out *BpfAppStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfAppStatus.
func (in *BpfAppStatus) DeepCopy() *BpfAppStatus {
	if in == nil {
		return nil
	}
	out := new(BpfAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplication) DeepCopyInto(out *BpfApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplication.
func (in *BpfApplication) DeepCopy() *BpfApplication {
	if in == nil {
		return nil
	}
	out := new(BpfApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplicationList) DeepCopyInto(out *BpfApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BpfApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplicationList.
func (in *BpfApplicationList) DeepCopy() *BpfApplicationList {
	if in == nil {
		return nil
	}
	out := new(BpfApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplicationProgram) DeepCopyInto(out *BpfApplicationProgram) {
	*out = *in
	if in.XDP != nil {
		in, out := &in.XDP, &out.XDP
		*out = new(XdpProgramInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.TC != nil {
		in, out := &in.TC, &out.TC
		*out = new(TcProgramInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.TCX != nil {
		in, out := &in.TCX, &out.TCX
		*out = new(TcxProgramInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Fentry != nil {
		in, out := &in.Fentry, &out.Fentry
		*out = new(FentryProgramInfo)
		**out = **in
	}
	if in.Fexit != nil {
		in, out := &in.Fexit, &out.Fexit
		*out = new(FexitProgramInfo)
		**out = **in
	}
	if in.Kprobe != nil {
		in, out := &in.Kprobe, &out.Kprobe
		*out = new(KprobeProgramInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Uprobe != nil {
		in, out := &in.Uprobe, &out.Uprobe
		*out = new(UprobeProgramInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Tracepoint != nil {
		in, out := &in.Tracepoint, &out.Tracepoint
		*out = new(TracepointProgramInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplicationProgram.
func (in *BpfApplicationProgram) DeepCopy() *BpfApplicationProgram {
	if in == nil {
		return nil
	}
	out := new(BpfApplicationProgram)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplicationProgramState) DeepCopyInto(out *BpfApplicationProgramState) {
	*out = *in
	in.BpfProgramStateCommon.DeepCopyInto(&out.BpfProgramStateCommon)
	if in.XDP != nil {
		in, out := &in.XDP, &out.XDP
		*out = new(XdpProgramInfoState)
		(*in).DeepCopyInto(*out)
	}
	if in.TC != nil {
		in, out := &in.TC, &out.TC
		*out = new(TcProgramInfoState)
		(*in).DeepCopyInto(*out)
	}
	if in.TCX != nil {
		in, out := &in.TCX, &out.TCX
		*out = new(TcxProgramInfoState)
		(*in).DeepCopyInto(*out)
	}
	if in.Fentry != nil {
		in, out := &in.Fentry, &out.Fentry
		*out = new(FentryProgramInfoState)
		(*in).DeepCopyInto(*out)
	}
	if in.Fexit != nil {
		in, out := &in.Fexit, &out.Fexit
		*out = new(FexitProgramInfoState)
		(*in).DeepCopyInto(*out)
	}
	if in.Kprobe != nil {
		in, out := &in.Kprobe, &out.Kprobe
		*out = new(KprobeProgramInfoState)
		(*in).DeepCopyInto(*out)
	}
	if in.Uprobe != nil {
		in, out := &in.Uprobe, &out.Uprobe
		*out = new(UprobeProgramInfoState)
		(*in).DeepCopyInto(*out)
	}
	if in.Tracepoint != nil {
		in, out := &in.Tracepoint, &out.Tracepoint
		*out = new(TracepointProgramInfoState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplicationProgramState.
func (in *BpfApplicationProgramState) DeepCopy() *BpfApplicationProgramState {
	if in == nil {
		return nil
	}
	out := new(BpfApplicationProgramState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplicationSpec) DeepCopyInto(out *BpfApplicationSpec) {
	*out = *in
	in.BpfAppCommon.DeepCopyInto(&out.BpfAppCommon)
	if in.Programs != nil {
		in, out := &in.Programs, &out.Programs
		*out = make([]BpfApplicationProgram, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplicationSpec.
func (in *BpfApplicationSpec) DeepCopy() *BpfApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(BpfApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplicationState) DeepCopyInto(out *BpfApplicationState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplicationState.
func (in *BpfApplicationState) DeepCopy() *BpfApplicationState {
	if in == nil {
		return nil
	}
	out := new(BpfApplicationState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfApplicationState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplicationStateList) DeepCopyInto(out *BpfApplicationStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BpfApplicationState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplicationStateList.
func (in *BpfApplicationStateList) DeepCopy() *BpfApplicationStateList {
	if in == nil {
		return nil
	}
	out := new(BpfApplicationStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfApplicationStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfApplicationStateSpec) DeepCopyInto(out *BpfApplicationStateSpec) {
	*out = *in
	if in.Programs != nil {
		in, out := &in.Programs, &out.Programs
		*out = make([]BpfApplicationProgramState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfApplicationStateSpec.
func (in *BpfApplicationStateSpec) DeepCopy() *BpfApplicationStateSpec {
	if in == nil {
		return nil
	}
	out := new(BpfApplicationStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfNsApplication) DeepCopyInto(out *BpfNsApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfNsApplication.
func (in *BpfNsApplication) DeepCopy() *BpfNsApplication {
	if in == nil {
		return nil
	}
	out := new(BpfNsApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfNsApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfNsApplicationList) DeepCopyInto(out *BpfNsApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BpfNsApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfNsApplicationList.
func (in *BpfNsApplicationList) DeepCopy() *BpfNsApplicationList {
	if in == nil {
		return nil
	}
	out := new(BpfNsApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfNsApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfNsApplicationProgram) DeepCopyInto(out *BpfNsApplicationProgram) {
	*out = *in
	if in.XDP != nil {
		in, out := &in.XDP, &out.XDP
		*out = new(XdpNsProgramInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.TC != nil {
		in, out := &in.TC, &out.TC
		*out = new(TcNsProgramInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.TCX != nil {
		in, out := &in.TCX, &out.TCX
		*out = new(TcxNsProgramInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Uprobe != nil {
		in, out := &in.Uprobe, &out.Uprobe
		*out = new(UprobeNsProgramInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfNsApplicationProgram.
func (in *BpfNsApplicationProgram) DeepCopy() *BpfNsApplicationProgram {
	if in == nil {
		return nil
	}
	out := new(BpfNsApplicationProgram)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfNsApplicationProgramState) DeepCopyInto(out *BpfNsApplicationProgramState) {
	*out = *in
	in.BpfProgramStateCommon.DeepCopyInto(&out.BpfProgramStateCommon)
	if in.XDP != nil {
		in, out := &in.XDP, &out.XDP
		*out = new(XdpNsProgramInfoState)
		(*in).DeepCopyInto(*out)
	}
	if in.TC != nil {
		in, out := &in.TC, &out.TC
		*out = new(TcNsProgramInfoState)
		(*in).DeepCopyInto(*out)
	}
	if in.TCX != nil {
		in, out := &in.TCX, &out.TCX
		*out = new(TcxNsProgramInfoState)
		(*in).DeepCopyInto(*out)
	}
	if in.Uprobe != nil {
		in, out := &in.Uprobe, &out.Uprobe
		*out = new(UprobeNsProgramInfoState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfNsApplicationProgramState.
func (in *BpfNsApplicationProgramState) DeepCopy() *BpfNsApplicationProgramState {
	if in == nil {
		return nil
	}
	out := new(BpfNsApplicationProgramState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfNsApplicationSpec) DeepCopyInto(out *BpfNsApplicationSpec) {
	*out = *in
	in.BpfAppCommon.DeepCopyInto(&out.BpfAppCommon)
	if in.Programs != nil {
		in, out := &in.Programs, &out.Programs
		*out = make([]BpfNsApplicationProgram, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfNsApplicationSpec.
func (in *BpfNsApplicationSpec) DeepCopy() *BpfNsApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(BpfNsApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfNsApplicationState) DeepCopyInto(out *BpfNsApplicationState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfNsApplicationState.
func (in *BpfNsApplicationState) DeepCopy() *BpfNsApplicationState {
	if in == nil {
		return nil
	}
	out := new(BpfNsApplicationState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfNsApplicationState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfNsApplicationStateList) DeepCopyInto(out *BpfNsApplicationStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BpfNsApplicationState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfNsApplicationStateList.
func (in *BpfNsApplicationStateList) DeepCopy() *BpfNsApplicationStateList {
	if in == nil {
		return nil
	}
	out := new(BpfNsApplicationStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BpfNsApplicationStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfNsApplicationStateSpec) DeepCopyInto(out *BpfNsApplicationStateSpec) {
	*out = *in
	if in.Programs != nil {
		in, out := &in.Programs, &out.Programs
		*out = make([]BpfNsApplicationProgramState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfNsApplicationStateSpec.
func (in *BpfNsApplicationStateSpec) DeepCopy() *BpfNsApplicationStateSpec {
	if in == nil {
		return nil
	}
	out := new(BpfNsApplicationStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BpfProgramStateCommon) DeepCopyInto(out *BpfProgramStateCommon) {
	*out = *in
	if in.ProgramId != nil {
		in, out := &in.ProgramId, &out.ProgramId
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BpfProgramStateCommon.
func (in *BpfProgramStateCommon) DeepCopy() *BpfProgramStateCommon {
	if in == nil {
		return nil
	}
	out := new(BpfProgramStateCommon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BytecodeImage) DeepCopyInto(out *BytecodeImage) {
	*out = *in
	if in.ImagePullSecret != nil {
		in, out := &in.ImagePullSecret, &out.ImagePullSecret
		*out = new(ImagePullSecretSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BytecodeImage.
func (in *BytecodeImage) DeepCopy() *BytecodeImage {
	if in == nil {
		return nil
	}
	out := new(BytecodeImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BytecodeSelector) DeepCopyInto(out *BytecodeSelector) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(BytecodeImage)
		(*in).DeepCopyInto(*out)
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BytecodeSelector.
func (in *BytecodeSelector) DeepCopy() *BytecodeSelector {
	if in == nil {
		return nil
	}
	out := new(BytecodeSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerNsSelector) DeepCopyInto(out *ContainerNsSelector) {
	*out = *in
	in.Pods.DeepCopyInto(&out.Pods)
	if in.ContainerNames != nil {
		in, out := &in.ContainerNames, &out.ContainerNames
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerNsSelector.
func (in *ContainerNsSelector) DeepCopy() *ContainerNsSelector {
	if in == nil {
		return nil
	}
	out := new(ContainerNsSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerSelector) DeepCopyInto(out *ContainerSelector) {
	*out = *in
	in.Pods.DeepCopyInto(&out.Pods)
	if in.ContainerNames != nil {
		in, out := &in.ContainerNames, &out.ContainerNames
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerSelector.
func (in *ContainerSelector) DeepCopy() *ContainerSelector {
	if in == nil {
		return nil
	}
	out := new(ContainerSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FentryAttachInfo) DeepCopyInto(out *FentryAttachInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FentryAttachInfo.
func (in *FentryAttachInfo) DeepCopy() *FentryAttachInfo {
	if in == nil {
		return nil
	}
	out := new(FentryAttachInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FentryAttachInfoState) DeepCopyInto(out *FentryAttachInfoState) {
	*out = *in
	in.AttachInfoStateCommon.DeepCopyInto(&out.AttachInfoStateCommon)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FentryAttachInfoState.
func (in *FentryAttachInfoState) DeepCopy() *FentryAttachInfoState {
	if in == nil {
		return nil
	}
	out := new(FentryAttachInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FentryLoadInfo) DeepCopyInto(out *FentryLoadInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FentryLoadInfo.
func (in *FentryLoadInfo) DeepCopy() *FentryLoadInfo {
	if in == nil {
		return nil
	}
	out := new(FentryLoadInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FentryProgramInfo) DeepCopyInto(out *FentryProgramInfo) {
	*out = *in
	out.FentryLoadInfo = in.FentryLoadInfo
	out.FentryAttachInfo = in.FentryAttachInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FentryProgramInfo.
func (in *FentryProgramInfo) DeepCopy() *FentryProgramInfo {
	if in == nil {
		return nil
	}
	out := new(FentryProgramInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FentryProgramInfoState) DeepCopyInto(out *FentryProgramInfoState) {
	*out = *in
	out.FentryLoadInfo = in.FentryLoadInfo
	in.FentryAttachInfoState.DeepCopyInto(&out.FentryAttachInfoState)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FentryProgramInfoState.
func (in *FentryProgramInfoState) DeepCopy() *FentryProgramInfoState {
	if in == nil {
		return nil
	}
	out := new(FentryProgramInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FexitAttachInfo) DeepCopyInto(out *FexitAttachInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FexitAttachInfo.
func (in *FexitAttachInfo) DeepCopy() *FexitAttachInfo {
	if in == nil {
		return nil
	}
	out := new(FexitAttachInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FexitAttachInfoState) DeepCopyInto(out *FexitAttachInfoState) {
	*out = *in
	in.AttachInfoStateCommon.DeepCopyInto(&out.AttachInfoStateCommon)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FexitAttachInfoState.
func (in *FexitAttachInfoState) DeepCopy() *FexitAttachInfoState {
	if in == nil {
		return nil
	}
	out := new(FexitAttachInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FexitLoadInfo) DeepCopyInto(out *FexitLoadInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FexitLoadInfo.
func (in *FexitLoadInfo) DeepCopy() *FexitLoadInfo {
	if in == nil {
		return nil
	}
	out := new(FexitLoadInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FexitProgramInfo) DeepCopyInto(out *FexitProgramInfo) {
	*out = *in
	out.FexitLoadInfo = in.FexitLoadInfo
	out.FexitAttachInfo = in.FexitAttachInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FexitProgramInfo.
func (in *FexitProgramInfo) DeepCopy() *FexitProgramInfo {
	if in == nil {
		return nil
	}
	out := new(FexitProgramInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FexitProgramInfoState) DeepCopyInto(out *FexitProgramInfoState) {
	*out = *in
	out.FexitLoadInfo = in.FexitLoadInfo
	in.FexitAttachInfoState.DeepCopyInto(&out.FexitAttachInfoState)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FexitProgramInfoState.
func (in *FexitProgramInfoState) DeepCopy() *FexitProgramInfoState {
	if in == nil {
		return nil
	}
	out := new(FexitProgramInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSecretSelector) DeepCopyInto(out *ImagePullSecretSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSecretSelector.
func (in *ImagePullSecretSelector) DeepCopy() *ImagePullSecretSelector {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecretSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceSelector) DeepCopyInto(out *InterfaceSelector) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.PrimaryNodeInterface != nil {
		in, out := &in.PrimaryNodeInterface, &out.PrimaryNodeInterface
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceSelector.
func (in *InterfaceSelector) DeepCopy() *InterfaceSelector {
	if in == nil {
		return nil
	}
	out := new(InterfaceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KprobeAttachInfo) DeepCopyInto(out *KprobeAttachInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KprobeAttachInfo.
func (in *KprobeAttachInfo) DeepCopy() *KprobeAttachInfo {
	if in == nil {
		return nil
	}
	out := new(KprobeAttachInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KprobeAttachInfoState) DeepCopyInto(out *KprobeAttachInfoState) {
	*out = *in
	in.AttachInfoStateCommon.DeepCopyInto(&out.AttachInfoStateCommon)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KprobeAttachInfoState.
func (in *KprobeAttachInfoState) DeepCopy() *KprobeAttachInfoState {
	if in == nil {
		return nil
	}
	out := new(KprobeAttachInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KprobeProgramInfo) DeepCopyInto(out *KprobeProgramInfo) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]KprobeAttachInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KprobeProgramInfo.
func (in *KprobeProgramInfo) DeepCopy() *KprobeProgramInfo {
	if in == nil {
		return nil
	}
	out := new(KprobeProgramInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KprobeProgramInfoState) DeepCopyInto(out *KprobeProgramInfoState) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]KprobeAttachInfoState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KprobeProgramInfoState.
func (in *KprobeProgramInfoState) DeepCopy() *KprobeProgramInfoState {
	if in == nil {
		return nil
	}
	out := new(KprobeProgramInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcAttachInfo) DeepCopyInto(out *TcAttachInfo) {
	*out = *in
	in.InterfaceSelector.DeepCopyInto(&out.InterfaceSelector)
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = new(ContainerSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ProceedOn != nil {
		in, out := &in.ProceedOn, &out.ProceedOn
		*out = make([]TcProceedOnValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcAttachInfo.
func (in *TcAttachInfo) DeepCopy() *TcAttachInfo {
	if in == nil {
		return nil
	}
	out := new(TcAttachInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcAttachInfoState) DeepCopyInto(out *TcAttachInfoState) {
	*out = *in
	in.AttachInfoStateCommon.DeepCopyInto(&out.AttachInfoStateCommon)
	if in.ContainerPid != nil {
		in, out := &in.ContainerPid, &out.ContainerPid
		*out = new(int32)
		**out = **in
	}
	if in.ProceedOn != nil {
		in, out := &in.ProceedOn, &out.ProceedOn
		*out = make([]TcProceedOnValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcAttachInfoState.
func (in *TcAttachInfoState) DeepCopy() *TcAttachInfoState {
	if in == nil {
		return nil
	}
	out := new(TcAttachInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcNsAttachInfo) DeepCopyInto(out *TcNsAttachInfo) {
	*out = *in
	in.InterfaceSelector.DeepCopyInto(&out.InterfaceSelector)
	in.Containers.DeepCopyInto(&out.Containers)
	if in.ProceedOn != nil {
		in, out := &in.ProceedOn, &out.ProceedOn
		*out = make([]TcProceedOnValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcNsAttachInfo.
func (in *TcNsAttachInfo) DeepCopy() *TcNsAttachInfo {
	if in == nil {
		return nil
	}
	out := new(TcNsAttachInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcNsAttachInfoState) DeepCopyInto(out *TcNsAttachInfoState) {
	*out = *in
	in.AttachInfoStateCommon.DeepCopyInto(&out.AttachInfoStateCommon)
	if in.ProceedOn != nil {
		in, out := &in.ProceedOn, &out.ProceedOn
		*out = make([]TcProceedOnValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcNsAttachInfoState.
func (in *TcNsAttachInfoState) DeepCopy() *TcNsAttachInfoState {
	if in == nil {
		return nil
	}
	out := new(TcNsAttachInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcNsProgramInfo) DeepCopyInto(out *TcNsProgramInfo) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]TcNsAttachInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcNsProgramInfo.
func (in *TcNsProgramInfo) DeepCopy() *TcNsProgramInfo {
	if in == nil {
		return nil
	}
	out := new(TcNsProgramInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcNsProgramInfoState) DeepCopyInto(out *TcNsProgramInfoState) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]TcNsAttachInfoState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcNsProgramInfoState.
func (in *TcNsProgramInfoState) DeepCopy() *TcNsProgramInfoState {
	if in == nil {
		return nil
	}
	out := new(TcNsProgramInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcProgramInfo) DeepCopyInto(out *TcProgramInfo) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]TcAttachInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcProgramInfo.
func (in *TcProgramInfo) DeepCopy() *TcProgramInfo {
	if in == nil {
		return nil
	}
	out := new(TcProgramInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcProgramInfoState) DeepCopyInto(out *TcProgramInfoState) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]TcAttachInfoState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcProgramInfoState.
func (in *TcProgramInfoState) DeepCopy() *TcProgramInfoState {
	if in == nil {
		return nil
	}
	out := new(TcProgramInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcxAttachInfo) DeepCopyInto(out *TcxAttachInfo) {
	*out = *in
	in.InterfaceSelector.DeepCopyInto(&out.InterfaceSelector)
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = new(ContainerSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcxAttachInfo.
func (in *TcxAttachInfo) DeepCopy() *TcxAttachInfo {
	if in == nil {
		return nil
	}
	out := new(TcxAttachInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcxAttachInfoState) DeepCopyInto(out *TcxAttachInfoState) {
	*out = *in
	in.AttachInfoStateCommon.DeepCopyInto(&out.AttachInfoStateCommon)
	if in.ContainerPid != nil {
		in, out := &in.ContainerPid, &out.ContainerPid
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcxAttachInfoState.
func (in *TcxAttachInfoState) DeepCopy() *TcxAttachInfoState {
	if in == nil {
		return nil
	}
	out := new(TcxAttachInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcxNsAttachInfo) DeepCopyInto(out *TcxNsAttachInfo) {
	*out = *in
	in.InterfaceSelector.DeepCopyInto(&out.InterfaceSelector)
	in.Containers.DeepCopyInto(&out.Containers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcxNsAttachInfo.
func (in *TcxNsAttachInfo) DeepCopy() *TcxNsAttachInfo {
	if in == nil {
		return nil
	}
	out := new(TcxNsAttachInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcxNsAttachInfoState) DeepCopyInto(out *TcxNsAttachInfoState) {
	*out = *in
	in.AttachInfoStateCommon.DeepCopyInto(&out.AttachInfoStateCommon)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcxNsAttachInfoState.
func (in *TcxNsAttachInfoState) DeepCopy() *TcxNsAttachInfoState {
	if in == nil {
		return nil
	}
	out := new(TcxNsAttachInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcxNsProgramInfo) DeepCopyInto(out *TcxNsProgramInfo) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]TcxNsAttachInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcxNsProgramInfo.
func (in *TcxNsProgramInfo) DeepCopy() *TcxNsProgramInfo {
	if in == nil {
		return nil
	}
	out := new(TcxNsProgramInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcxNsProgramInfoState) DeepCopyInto(out *TcxNsProgramInfoState) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]TcxNsAttachInfoState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcxNsProgramInfoState.
func (in *TcxNsProgramInfoState) DeepCopy() *TcxNsProgramInfoState {
	if in == nil {
		return nil
	}
	out := new(TcxNsProgramInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcxProgramInfo) DeepCopyInto(out *TcxProgramInfo) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]TcxAttachInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcxProgramInfo.
func (in *TcxProgramInfo) DeepCopy() *TcxProgramInfo {
	if in == nil {
		return nil
	}
	out := new(TcxProgramInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcxProgramInfoState) DeepCopyInto(out *TcxProgramInfoState) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]TcxAttachInfoState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcxProgramInfoState.
func (in *TcxProgramInfoState) DeepCopy() *TcxProgramInfoState {
	if in == nil {
		return nil
	}
	out := new(TcxProgramInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracepointAttachInfo) DeepCopyInto(out *TracepointAttachInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracepointAttachInfo.
func (in *TracepointAttachInfo) DeepCopy() *TracepointAttachInfo {
	if in == nil {
		return nil
	}
	out := new(TracepointAttachInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracepointAttachInfoState) DeepCopyInto(out *TracepointAttachInfoState) {
	*out = *in
	in.AttachInfoStateCommon.DeepCopyInto(&out.AttachInfoStateCommon)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracepointAttachInfoState.
func (in *TracepointAttachInfoState) DeepCopy() *TracepointAttachInfoState {
	if in == nil {
		return nil
	}
	out := new(TracepointAttachInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracepointProgramInfo) DeepCopyInto(out *TracepointProgramInfo) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]TracepointAttachInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracepointProgramInfo.
func (in *TracepointProgramInfo) DeepCopy() *TracepointProgramInfo {
	if in == nil {
		return nil
	}
	out := new(TracepointProgramInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracepointProgramInfoState) DeepCopyInto(out *TracepointProgramInfoState) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]TracepointAttachInfoState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracepointProgramInfoState.
func (in *TracepointProgramInfoState) DeepCopy() *TracepointProgramInfoState {
	if in == nil {
		return nil
	}
	out := new(TracepointProgramInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UprobeAttachInfo) DeepCopyInto(out *UprobeAttachInfo) {
	*out = *in
	if in.Pid != nil {
		in, out := &in.Pid, &out.Pid
		*out = new(int32)
		**out = **in
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = new(ContainerSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UprobeAttachInfo.
func (in *UprobeAttachInfo) DeepCopy() *UprobeAttachInfo {
	if in == nil {
		return nil
	}
	out := new(UprobeAttachInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UprobeAttachInfoState) DeepCopyInto(out *UprobeAttachInfoState) {
	*out = *in
	in.AttachInfoStateCommon.DeepCopyInto(&out.AttachInfoStateCommon)
	if in.Pid != nil {
		in, out := &in.Pid, &out.Pid
		*out = new(int32)
		**out = **in
	}
	if in.ContainerPid != nil {
		in, out := &in.ContainerPid, &out.ContainerPid
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UprobeAttachInfoState.
func (in *UprobeAttachInfoState) DeepCopy() *UprobeAttachInfoState {
	if in == nil {
		return nil
	}
	out := new(UprobeAttachInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UprobeNsAttachInfo) DeepCopyInto(out *UprobeNsAttachInfo) {
	*out = *in
	if in.Pid != nil {
		in, out := &in.Pid, &out.Pid
		*out = new(int32)
		**out = **in
	}
	in.Containers.DeepCopyInto(&out.Containers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UprobeNsAttachInfo.
func (in *UprobeNsAttachInfo) DeepCopy() *UprobeNsAttachInfo {
	if in == nil {
		return nil
	}
	out := new(UprobeNsAttachInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UprobeNsAttachInfoState) DeepCopyInto(out *UprobeNsAttachInfoState) {
	*out = *in
	in.AttachInfoStateCommon.DeepCopyInto(&out.AttachInfoStateCommon)
	if in.Pid != nil {
		in, out := &in.Pid, &out.Pid
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UprobeNsAttachInfoState.
func (in *UprobeNsAttachInfoState) DeepCopy() *UprobeNsAttachInfoState {
	if in == nil {
		return nil
	}
	out := new(UprobeNsAttachInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UprobeNsProgramInfo) DeepCopyInto(out *UprobeNsProgramInfo) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]UprobeNsAttachInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UprobeNsProgramInfo.
func (in *UprobeNsProgramInfo) DeepCopy() *UprobeNsProgramInfo {
	if in == nil {
		return nil
	}
	out := new(UprobeNsProgramInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UprobeNsProgramInfoState) DeepCopyInto(out *UprobeNsProgramInfoState) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]UprobeNsAttachInfoState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UprobeNsProgramInfoState.
func (in *UprobeNsProgramInfoState) DeepCopy() *UprobeNsProgramInfoState {
	if in == nil {
		return nil
	}
	out := new(UprobeNsProgramInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UprobeProgramInfo) DeepCopyInto(out *UprobeProgramInfo) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]UprobeAttachInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UprobeProgramInfo.
func (in *UprobeProgramInfo) DeepCopy() *UprobeProgramInfo {
	if in == nil {
		return nil
	}
	out := new(UprobeProgramInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UprobeProgramInfoState) DeepCopyInto(out *UprobeProgramInfoState) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]UprobeAttachInfoState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UprobeProgramInfoState.
func (in *UprobeProgramInfoState) DeepCopy() *UprobeProgramInfoState {
	if in == nil {
		return nil
	}
	out := new(UprobeProgramInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdpAttachInfo) DeepCopyInto(out *XdpAttachInfo) {
	*out = *in
	in.InterfaceSelector.DeepCopyInto(&out.InterfaceSelector)
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = new(ContainerSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ProceedOn != nil {
		in, out := &in.ProceedOn, &out.ProceedOn
		*out = make([]XdpProceedOnValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdpAttachInfo.
func (in *XdpAttachInfo) DeepCopy() *XdpAttachInfo {
	if in == nil {
		return nil
	}
	out := new(XdpAttachInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdpAttachInfoState) DeepCopyInto(out *XdpAttachInfoState) {
	*out = *in
	in.AttachInfoStateCommon.DeepCopyInto(&out.AttachInfoStateCommon)
	if in.ContainerPid != nil {
		in, out := &in.ContainerPid, &out.ContainerPid
		*out = new(int32)
		**out = **in
	}
	if in.ProceedOn != nil {
		in, out := &in.ProceedOn, &out.ProceedOn
		*out = make([]XdpProceedOnValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdpAttachInfoState.
func (in *XdpAttachInfoState) DeepCopy() *XdpAttachInfoState {
	if in == nil {
		return nil
	}
	out := new(XdpAttachInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdpNsAttachInfo) DeepCopyInto(out *XdpNsAttachInfo) {
	*out = *in
	in.InterfaceSelector.DeepCopyInto(&out.InterfaceSelector)
	in.Containers.DeepCopyInto(&out.Containers)
	if in.ProceedOn != nil {
		in, out := &in.ProceedOn, &out.ProceedOn
		*out = make([]XdpProceedOnValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdpNsAttachInfo.
func (in *XdpNsAttachInfo) DeepCopy() *XdpNsAttachInfo {
	if in == nil {
		return nil
	}
	out := new(XdpNsAttachInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdpNsAttachInfoState) DeepCopyInto(out *XdpNsAttachInfoState) {
	*out = *in
	in.AttachInfoStateCommon.DeepCopyInto(&out.AttachInfoStateCommon)
	if in.ProceedOn != nil {
		in, out := &in.ProceedOn, &out.ProceedOn
		*out = make([]XdpProceedOnValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdpNsAttachInfoState.
func (in *XdpNsAttachInfoState) DeepCopy() *XdpNsAttachInfoState {
	if in == nil {
		return nil
	}
	out := new(XdpNsAttachInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdpNsProgramInfo) DeepCopyInto(out *XdpNsProgramInfo) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]XdpNsAttachInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdpNsProgramInfo.
func (in *XdpNsProgramInfo) DeepCopy() *XdpNsProgramInfo {
	if in == nil {
		return nil
	}
	out := new(XdpNsProgramInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdpNsProgramInfoState) DeepCopyInto(out *XdpNsProgramInfoState) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]XdpNsAttachInfoState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdpNsProgramInfoState.
func (in *XdpNsProgramInfoState) DeepCopy() *XdpNsProgramInfoState {
	if in == nil {
		return nil
	}
	out := new(XdpNsProgramInfoState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdpProgramInfo) DeepCopyInto(out *XdpProgramInfo) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]XdpAttachInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdpProgramInfo.
func (in *XdpProgramInfo) DeepCopy() *XdpProgramInfo {
	if in == nil {
		return nil
	}
	out := new(XdpProgramInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdpProgramInfoState) DeepCopyInto(out *XdpProgramInfoState) {
	*out = *in
	if in.AttachPoints != nil {
		in, out := &in.AttachPoints, &out.AttachPoints
		*out = make([]XdpAttachInfoState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdpProgramInfoState.
func (in *XdpProgramInfoState) DeepCopy() *XdpProgramInfoState {
	if in == nil {
		return nil
	}
	out := new(XdpProgramInfoState)
	in.DeepCopyInto(out)
	return out
}
