/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/bpfman/bpfman-operator/pkg/client/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// BpfApplications returns a BpfApplicationInformer.
	BpfApplications() BpfApplicationInformer
	// BpfNsApplications returns a BpfNsApplicationInformer.
	BpfNsApplications() BpfNsApplicationInformer
	// BpfNsPrograms returns a BpfNsProgramInformer.
	BpfNsPrograms() BpfNsProgramInformer
	// BpfPrograms returns a BpfProgramInformer.
	BpfPrograms() BpfProgramInformer
	// FentryPrograms returns a FentryProgramInformer.
	FentryPrograms() FentryProgramInformer
	// FexitPrograms returns a FexitProgramInformer.
	FexitPrograms() FexitProgramInformer
	// KprobePrograms returns a KprobeProgramInformer.
	KprobePrograms() KprobeProgramInformer
	// TcNsPrograms returns a TcNsProgramInformer.
	TcNsPrograms() TcNsProgramInformer
	// TcPrograms returns a TcProgramInformer.
	TcPrograms() TcProgramInformer
	// TcxNsPrograms returns a TcxNsProgramInformer.
	TcxNsPrograms() TcxNsProgramInformer
	// TcxPrograms returns a TcxProgramInformer.
	TcxPrograms() TcxProgramInformer
	// TracepointPrograms returns a TracepointProgramInformer.
	TracepointPrograms() TracepointProgramInformer
	// UprobeNsPrograms returns a UprobeNsProgramInformer.
	UprobeNsPrograms() UprobeNsProgramInformer
	// UprobePrograms returns a UprobeProgramInformer.
	UprobePrograms() UprobeProgramInformer
	// XdpNsPrograms returns a XdpNsProgramInformer.
	XdpNsPrograms() XdpNsProgramInformer
	// XdpPrograms returns a XdpProgramInformer.
	XdpPrograms() XdpProgramInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// BpfApplications returns a BpfApplicationInformer.
func (v *version) BpfApplications() BpfApplicationInformer {
	return &bpfApplicationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// BpfNsApplications returns a BpfNsApplicationInformer.
func (v *version) BpfNsApplications() BpfNsApplicationInformer {
	return &bpfNsApplicationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// BpfNsPrograms returns a BpfNsProgramInformer.
func (v *version) BpfNsPrograms() BpfNsProgramInformer {
	return &bpfNsProgramInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// BpfPrograms returns a BpfProgramInformer.
func (v *version) BpfPrograms() BpfProgramInformer {
	return &bpfProgramInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// FentryPrograms returns a FentryProgramInformer.
func (v *version) FentryPrograms() FentryProgramInformer {
	return &fentryProgramInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// FexitPrograms returns a FexitProgramInformer.
func (v *version) FexitPrograms() FexitProgramInformer {
	return &fexitProgramInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// KprobePrograms returns a KprobeProgramInformer.
func (v *version) KprobePrograms() KprobeProgramInformer {
	return &kprobeProgramInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TcNsPrograms returns a TcNsProgramInformer.
func (v *version) TcNsPrograms() TcNsProgramInformer {
	return &tcNsProgramInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TcPrograms returns a TcProgramInformer.
func (v *version) TcPrograms() TcProgramInformer {
	return &tcProgramInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TcxNsPrograms returns a TcxNsProgramInformer.
func (v *version) TcxNsPrograms() TcxNsProgramInformer {
	return &tcxNsProgramInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TcxPrograms returns a TcxProgramInformer.
func (v *version) TcxPrograms() TcxProgramInformer {
	return &tcxProgramInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TracepointPrograms returns a TracepointProgramInformer.
func (v *version) TracepointPrograms() TracepointProgramInformer {
	return &tracepointProgramInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// UprobeNsPrograms returns a UprobeNsProgramInformer.
func (v *version) UprobeNsPrograms() UprobeNsProgramInformer {
	return &uprobeNsProgramInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// UprobePrograms returns a UprobeProgramInformer.
func (v *version) UprobePrograms() UprobeProgramInformer {
	return &uprobeProgramInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// XdpNsPrograms returns a XdpNsProgramInformer.
func (v *version) XdpNsPrograms() XdpNsProgramInformer {
	return &xdpNsProgramInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// XdpPrograms returns a XdpProgramInformer.
func (v *version) XdpPrograms() XdpProgramInformer {
	return &xdpProgramInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
