/*
Copyright 2023 The bpfman Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/bpfman/bpfman-operator/pkg/client/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// BpfApplications returns a BpfApplicationInformer.
	BpfApplications() BpfApplicationInformer
	// BpfApplicationStates returns a BpfApplicationStateInformer.
	BpfApplicationStates() BpfApplicationStateInformer
	// ClusterBpfApplications returns a ClusterBpfApplicationInformer.
	ClusterBpfApplications() ClusterBpfApplicationInformer
	// ClusterBpfApplicationStates returns a ClusterBpfApplicationStateInformer.
	ClusterBpfApplicationStates() ClusterBpfApplicationStateInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// BpfApplications returns a BpfApplicationInformer.
func (v *version) BpfApplications() BpfApplicationInformer {
	return &bpfApplicationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// BpfApplicationStates returns a BpfApplicationStateInformer.
func (v *version) BpfApplicationStates() BpfApplicationStateInformer {
	return &bpfApplicationStateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ClusterBpfApplications returns a ClusterBpfApplicationInformer.
func (v *version) ClusterBpfApplications() ClusterBpfApplicationInformer {
	return &clusterBpfApplicationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ClusterBpfApplicationStates returns a ClusterBpfApplicationStateInformer.
func (v *version) ClusterBpfApplicationStates() ClusterBpfApplicationStateInformer {
	return &clusterBpfApplicationStateInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
